name: "learning"
type: "python:3.11.1"

relationships:
  database: "db:postgresql"

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET djangoo.wsgi:application"
  locations:
    "/":
      passthru: true
    "static":
      root: "static"
      expirse: 1h
      allow: true

disk: 512

mounts:
  "logs":
    source: local
    source_path: logs

hooks:
  build: | 
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirments_remote.txt
    
    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy: |
    python manafe.py migrate
